# <div style="display:fill;border-radius:5px;background-color:#676F9F;letter-spacing:0.5px;overflow:hidden"><p style="padding:20px;color:#F1EFF5;overflow:hidden;margin:0;font-size:150%;font-style: Helvetica;text-align:center"><b></b>WHAT IF DOCTORüßë‚Äç‚öïÔ∏è PREPARES AN AI MODEL??ü§î</p></div>

In the previous notebook, I have prepared a dataset which consists of only numbers in the form I wanted. But the real world dataset doesn't match the same.So, lets change our dataset a little bit so that it is similar to the one we are aspiring for...

## <font color='#4287f5'>Importing necessary libraries...</font>

In [1]:
import pandas as pd                       # library for data manipulation (data cleaning,analysing...)
import numpy as np                        # library for numerical computation
import matplotlib.pyplot as plt           # library for data visualization which is built on NumPy arrays
%matplotlib inline
import seaborn as sns                     # library for data visualization built on top of matplotlib and 
                                          # closely integrated with pandas data structures in Python.

import random

import warnings                           # to avoid warning flash
warnings.filterwarnings('ignore')

# Other libraries will be imported in the following steps as the process moves....

In [2]:
df = pd.read_csv(r'D:\DSF\PROJECTPRO\MEDICAL_PROJECTS\2.HEMATOLOGICAL DISORDER(ANAEMIA)\Anaemia.csv')

In [3]:
df.columns

Index(['ID', 'age', 'sex', 'Retic_count', 'Bilirubin_count', 'LDH_count',
       'Coombs_test', 'Peripheral_Smear', 'Ferritin_level',
       'Hb_electrophoresis', 'Other_blood_cell_count\(Pancytopenia +/-)',
       'Serum_Creatinine', 'TSH_Level', 'Serum_electrophoresis',
       'B12_or_Folate_levels', 'CLASS'],
      dtype='object')

In [4]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1,1000,1000,1000,8,1000,1000,14,1000,1000,1000,1000,70
1,1,51,1,1,1000,1000,1000,8,1000,1000,14,1000,1000,1000,1000,70
2,2,32,0,2,3,3,1000,1000,1000,1000,1000,1000,1000,1000,1000,10
3,3,35,0,2,4,4,5,1000,1000,1000,1000,1000,1000,1000,1000,20
4,4,58,1,2,3,3,1000,1000,1000,1000,1000,1000,1000,1000,1000,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,1,1000,1000,1000,9,1000,1000,1000,1000,1000,1000,22,110
984,996,48,1,1,1000,1000,1000,8,1000,1000,14,1000,1000,1000,1000,70
985,997,58,1,0,1000,1000,1000,7,10,1000,1000,1000,1000,1000,1000,40
986,998,60,1,2,4,4,5,1000,1000,1000,1000,1000,1000,1000,1000,20
987,1000,55,1,2,3,3,1000,1000,1000,1000,1000,1000,1000,1000,1000,10

In [5]:
df['CLASS'].value_counts()

10     169
40     168
60      97
70      92
110     86
120     81
20      80
50      70
30      68
100     45
90      22
80      10
Name: CLASS, dtype: int64

By the way, what are these 10,20,30,40 and so on which are present in 'CLASS' column. Lets label these numbers...

In [6]:
df = df.replace({'CLASS':{10:'Acute_or_Chronic_blood_loss',
                            20:'Aquired_hemolytic_Anemia', 
                            30:'Congenital_hemolytic_Anemia', 
                            40:'Iron_deficiency_Anemia', 
                            50:'Thalassemia', 
                            60:'Anemia_of_chronic_disorder',
                            70:'Aplastic_anemia', 
                            80:'multiple_myeloma',
                            90:'hypothyroidism',
                            100:'chronic_kidney_disease',
                            110:'B12_deficiency',
                            120:'eval_for_systemic_disorder'}})

In [7]:
df['CLASS'].value_counts()

Acute_or_Chronic_blood_loss    169
Iron_deficiency_Anemia         168
Anemia_of_chronic_disorder      97
Aplastic_anemia                 92
B12_deficiency                  86
eval_for_systemic_disorder      81
Aquired_hemolytic_Anemia        80
Thalassemia                     70
Congenital_hemolytic_Anemia     68
chronic_kidney_disease          45
hypothyroidism                  22
multiple_myeloma                10
Name: CLASS, dtype: int64

Also, what are these '1000' values, it specifies the test is not done...

In [8]:
# lets replace these '1000' values..
df.replace(1000,'not_done',inplace = True)

In [9]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,2,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,2,4,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,2,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,1,not_done,not_done,not_done,9,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0,not_done,not_done,not_done,7,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,2,4,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,2,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [10]:
df.shape

(988, 16)

As I have told before, I want my dataset to look real. So,lets change the values of each features...

In [11]:
# a function to convert reticulocyte count values in the correct format
def convert_retic_count(x):
    if x == 0:                         
        return round(random.uniform(0,0.5),2)
    elif x == 1:           
        return round(random.uniform(0.5,2.5),2)
    else:
        return round(random.uniform(2.5,6.0),2)

In [12]:
df['Retic_count'] = df['Retic_count'].apply(lambda x: convert_retic_count(x))

In [13]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,4,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,9,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,7,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,4,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,3,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [14]:
# a function to convert bilirubin count values in the correct format
def convert_bilirubin_count(x):
    if x == 3:              #normal
        return round(random.uniform(0.1,0.8),2)
    elif x == 4:
        return round(random.uniform(0.8,8.0),2)                         #high
    else:
        return x

In [15]:
df['Bilirubin_count'] = df['Bilirubin_count'].apply(lambda x: convert_bilirubin_count(x))

In [16]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,9,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,7,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,4,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,3,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [17]:
# a function to convert LDH count values in the correct format
def convert_LDH_count(x):
    if x == 3:              #normal
        return random.randint(5,240)
    elif x == 4:
        return random.randint(240,600)                       #high
    else:
        return x

In [18]:
df['LDH_count'] = df['LDH_count'].apply(lambda x: convert_LDH_count(x))

In [19]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,9,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,7,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,5,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [20]:
# a function to convert Coombs test values in the correct format
def convert_Coombs_test(x):
    if x == 5:              
        return 'positive'
    elif x == 6:
        return 'negative'                    
    else:
        return x

In [21]:
df['Coombs_test'] = df['Coombs_test'].apply(lambda x:convert_Coombs_test(x))

In [22]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,9,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,8,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,7,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [23]:
# a function to convert Peripheral smear values in the correct format
def convert_Peripheral_Smear(x):
    if x == 7:              
        return 'microcytic'
    elif x == 8:
        return 'normocytic'
    elif x == 9:
        return 'macrocytic'
    else:
        return x

In [24]:
df['Peripheral_Smear'] = df['Peripheral_Smear'].apply(lambda x: convert_Peripheral_Smear(x))

In [25]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,10,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [26]:
# a function to convert Ferritin_level values in the correct format
def convert_Ferritin_level(x):
    if x == 10:                         #low
        return random.randint(2,18)
    elif x == 11:           #normal(18 to 200ng/ml)
        return random.randint(18,200)
    else:
        return x

In [27]:
df['Ferritin_level'] = df['Ferritin_level'].apply(lambda x:convert_Ferritin_level(x))

In [28]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [29]:
# a function to convert Hb_electrophoresis values in the correct format
def convert_Hb_electrophoresis(x):
    if x == 12:                       
        return 'HbA2,HbF'
    elif x == 13:          
        return 'normal'
    else:
        return x

In [30]:
df['Hb_electrophoresis'] = df['Hb_electrophoresis'].apply(lambda x: convert_Hb_electrophoresis(x))

In [31]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,14,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [32]:
# a function to convert blood cell count values in the correct format
def convert_blood_cell_count(x):
    if x == 14:                         
        return 'pancytopenia_present'
    elif x == 15:         
        return 'normal_count'
    else:
        return x

In [33]:
df['Other_blood_cell_count\(Pancytopenia +/-)'] = df['Other_blood_cell_count\(Pancytopenia +/-)'].apply(lambda x:convert_blood_cell_count(x))

In [34]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [35]:
# a function to convert Serum_Creatinine values in the correct format
def convert_Serum_Creatinine(x):
    if x == 16:                         #normal(0.6 to 1.2mg/dl)
        return round(random.uniform(0.6,1.2),1)
    elif x == 17:           
        return round(random.uniform(1.2,10.0),1)
    else:
        return x

In [36]:
df['Serum_Creatinine'] = df['Serum_Creatinine'].apply(lambda x: convert_Serum_Creatinine(x))

In [37]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [38]:
# a function to convert TSH_Level values in the correct format
def convert_TSH_Level(x):
    if x == 18:                         #normal(0.5 to 5.0(¬µU/mL))
        return round(random.uniform(0.5,5.0),2)
    elif x == 19:           
        return round(random.uniform(5.0,10.0),2)
    else:
        return x

In [39]:
df['TSH_Level'] = df['TSH_Level'].apply(lambda x: convert_TSH_Level(x))

In [40]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [41]:
# a function to convert Serum_electrophoresis values in the correct format
def convert_Serum_electrophoresis(x):
    if x == 21:                     
        return 'M-spike'
    elif x == 20:           
        return 'normal'
    else:
        return x

In [42]:
df['Serum_electrophoresis'] = df['Serum_electrophoresis'].apply(lambda x: convert_Serum_electrophoresis(x))

In [43]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,B12_or_Folate_levels,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

Next, I convert 'B12 or Folate level' column as 'Vit_B12_level' because folate level testing is rarely done nowdays.

In [44]:
df.rename(columns = {'B12_or_Folate_levels':'Vit_B12_level'},inplace = True)

In [45]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,Vit_B12_level,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,22,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

In [46]:
# a function to convert Vit_B12_level values in the correct format
def convert_Vit_B12_level(x):
    if x == 22:                         #low
        return random.randint(10,190)
    elif x == 23:           #normal(190 to 950pg/ml)
        return random.randint(190,950)
    else:
        return x

In [47]:
df['Vit_B12_level'] = df['Vit_B12_level'].apply(lambda x: convert_Vit_B12_level(x))

In [48]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,Vit_B12_level,CLASS
0,0,61,0,1.21,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
1,1,51,1,1.77,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,not_done,not_done,not_done,macrocytic,not_done,not_done,not_done,not_done,not_done,not_done,159,B12_deficiency
984,996,48,1,1.98,not_done,not_done,not_done,normocytic,not_done,not_done,pancytopenia_present,not_done,not_done,not_done,not_done,Aplastic_anemia
985,997,58,1,0.40,not_done,not_done,not_done,microcytic,2,not_done,not_done,not_done,not_done,not_done,not_done,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,not_done,Acute_or_Chronic_blood_loss

Now,our dataframe looks like the real one but one thing is so much depressing i.e, most of the feature values are filled with 'not_done' values. The features like 'Bilirubin_count','Peripheral_Smear','blood_cell_count','Serum_Creatinine','TSH_Level' and others are usually routinely done (depends on the hospital protocol). So, instead of inserting 'not_done' values, we will replace those with the normal values of the respective feature.

In [49]:
rows = df[df['Bilirubin_count'] == 'not_done'].index.tolist()

In [50]:
df.loc[rows,'Bilirubin_count'] = df['Bilirubin_count'].apply(lambda x: round(random.uniform(0.1, 0.8), 2))

In [51]:
rows = df[df['LDH_count'] == 'not_done'].index.tolist()

In [52]:
df.loc[rows,'LDH_count'] = df['LDH_count'].apply(lambda x: random.randint(5, 240))

In [53]:
rows = df[df['Peripheral_Smear'] == 'not_done'].index.tolist()

In [54]:
df.loc[rows,'Peripheral_Smear'] = df['Peripheral_Smear'].apply(lambda x: 'normocytic' )

In [55]:
rows = df[df['Ferritin_level'] == 'not_done'].index.tolist()

In [56]:
df.loc[rows,'Ferritin_level'] = df['Ferritin_level'].apply(lambda x: random.randint(18,200) )

In [57]:
rows = df[df['Other_blood_cell_count\(Pancytopenia +/-)'] == 'not_done'].index.tolist()

In [58]:
df.loc[rows,'Other_blood_cell_count\(Pancytopenia +/-)'] = df['Other_blood_cell_count\(Pancytopenia +/-)'].apply(lambda x: 'normal_count' )

In [59]:
rows = df[df['Serum_Creatinine'] == 'not_done'].index.tolist()

In [60]:
df.loc[rows,'Serum_Creatinine'] = df['Serum_Creatinine'].apply(lambda x: round(random.uniform(0.6,1.1),2))

In [61]:
rows = df[df['TSH_Level'] == 'not_done'].index.tolist()

In [62]:
df.loc[rows,'TSH_Level'] = df['TSH_Level'].apply(lambda x: round(random.uniform(0.5,5.0),2))

In [63]:
rows = df[df['Vit_B12_level'] == 'not_done'].index.tolist()

In [64]:
df.loc[rows,'Vit_B12_level'] = df['Vit_B12_level'].apply(lambda x: random.randint(190,950))

In [65]:
df

,ID,age,sex,Retic_count,Bilirubin_count,LDH_count,Coombs_test,Peripheral_Smear,Ferritin_level,Hb_electrophoresis,Other_blood_cell_count\(Pancytopenia +/-),Serum_Creatinine,TSH_Level,Serum_electrophoresis,Vit_B12_level,CLASS
0,0,61,0,1.21,0.5,154,not_done,normocytic,165,not_done,pancytopenia_present,0.68,3.5,not_done,389,Aplastic_anemia
1,1,51,1,1.77,0.75,54,not_done,normocytic,148,not_done,pancytopenia_present,1.1,3.42,not_done,678,Aplastic_anemia
2,2,32,0,5.68,0.6,82,not_done,normocytic,139,not_done,normal_count,0.94,3.5,not_done,237,Acute_or_Chronic_blood_loss
3,3,35,0,3.86,0.85,341,positive,normocytic,135,not_done,normal_count,0.91,3.28,not_done,327,Aquired_hemolytic_Anemia
4,4,58,1,4.60,0.66,236,not_done,normocytic,38,not_done,normal_count,1.1,1.25,not_done,808,Acute_or_Chronic_blood_loss
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,995,43,1,2.38,0.6,133,not_done,macrocytic,103,not_done,normal_count,0.89,2.12,not_done,159,B12_deficiency
984,996,48,1,1.98,0.55,95,not_done,normocytic,113,not_done,pancytopenia_present,0.9,0.85,not_done,782,Aplastic_anemia
985,997,58,1,0.40,0.28,104,not_done,microcytic,2,not_done,normal_count,0.67,3.36,not_done,219,Iron_deficiency_Anemia
986,998,60,1,4.08,6.03,392,positive,normocytic,167,not_done,normal_count,0.93,4.33,not_done,683,Aquired_hemolytic_Anemia
987,not_done,55,1,3.70,0.4,77,not_done,normocytic,114,not_done,normal_count,0.93,0.92,not_done,785,Acute_or_Chronic_blood_loss

I have left the features like 'Hb_electrophoresis','Serum_electrophoresis' as it is because these tests are usually not done unless indicated.

So,now our dataframe looks similar to the real-world dataset (I hope so). Before proceeding to the next data_science pipelines, I want to share some of the lab test facts here. The very features which I had selected here inorder to build the 'Anaemia_classification_AI' will not be available in the same order as I have built here. Infact,some of the tests may be missing. The feature like 'Bilirubin_count' will be available under 'Liver_Function_Test' so that if we want real_world 'Bilirubin_count' values, we have to search under 'Liver_Function_Test' column in the lab report.

## <font color='#4287f5'>Lets save the dataset...</font>

In [66]:
df.to_csv(r'D:\DSF\PROJECTPRO\MEDICAL_PROJECTS\2.HEMATOLOGICAL DISORDER(ANAEMIA)\real_anemia.csv',index = False)